version: '3.8'

services:
  postgres-db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: password
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend-define:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3003:3003'
    restart: always
    depends_on:
      - postgres-db
    environment:
      DATABASE_URL: 'postgresql://myuser:password@postgres-db:5432/mydatabase'

volumes:
  postgres_data:
